version: '3.9'

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/podtgresql/data

  backend:
    build:
      context: ./backend/projeto
    volumes:
      - ./backend/projeto:/app
    ports: 
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: 
      context: ./frontend/staycation-v2
    volumes:
      - ./frontend/staycation-v2:/app
      - /app/node_modules
    ports: 
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/
    command: npm run dev

volumes:
  postgres_data:



