# Generated by Django 5.1.7 on 2025-05-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='descricao',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='numero_hospedes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='preco',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='regras',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='titulo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imovel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
