# Generated by Django 5.1.7 on 2025-05-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_imovel_descricao_imovel_numero_hospedes_imovel_preco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='comodidades',
            field=models.ManyToManyField(blank=True, null=True, to='imoveis.comodidade'),
        ),
    ]
