# Generated by Django 5.1.7 on 2025-05-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_alter_imovel_comodidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco_imovel',
            name='bairro',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
