# Generated by Django 5.1.7 on 2025-05-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0004_endereco_imovel_bairro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco_imovel',
            name='pais',
        ),
        migrations.AlterField(
            model_name='imovel',
            name='comodidades',
            field=models.ManyToManyField(blank=True, to='imoveis.comodidade'),
        ),
    ]
