# Generated by Django 5.1.7 on 2025-05-14 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0005_remove_endereco_imovel_pais_alter_imovel_comodidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagem_imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imoveis/')),
                ('legenda', models.CharField(blank=True, max_length=255)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.imovel')),
            ],
        ),
    ]
