# Generated by Django 5.1.7 on 2025-05-21 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0007_imovel_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem_imovel',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='imoveis.imovel'),
        ),
    ]
