# Generated by Django 5.1.7 on 2025-05-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0008_alter_imagem_imovel_imovel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='id_reserva',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
