# Generated by Django 5.1.7 on 2025-04-08 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chacara',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('Descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('capacidade', models.IntegerField(default=0)),
                ('cep', models.CharField(help_text='Formato: XXXXX-XXX', max_length=9, validators=[django.core.validators.RegexValidator(message='CEP inválido. Use o formato XXXXX-XXX ou XXXXXXXX.', regex='^\\d{5}-?\\d{3}$')], verbose_name='CEP')),
            ],
        ),
    ]
