# Generated by Django 5.1.7 on 2025-04-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_chacara'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('visitante', 'Visitante'), ('locatario', 'Locatario'), ('proprietario', 'Prorietario')], default='locatario', max_length=12),
        ),
    ]
