# Generated by Django 5.1.7 on 2025-04-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_usuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('visitante', 'Visitante'), ('locatario', 'Locatario'), ('proprietario', 'proprietario')], default='visitante', max_length=13),
        ),
    ]
