# Generated by Django 5.1.7 on 2025-04-29 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cadastro', '0005_endereco_usuario_cpf_usuario_datanascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chacara',
            name='cep',
            field=models.CharField(help_text='Formato: XXXXX-XXX', max_length=9, validators=[django.core.validators.RegexValidator(message='CEP inválido. Use o formato XXXXX-XXX ou XXXXXXXX.', regex='^d{5}-?\\d{3}$')], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
    ]
