# Generated by Django 5.1.7 on 2025-04-30 23:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_alter_chacara_cep_alter_usuario_telefone_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usuario',
            name='unique_email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='endereco',
        ),
        migrations.AddField(
            model_name='endereco',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chacara',
            name='cep',
            field=models.CharField(help_text='Formato: XXXXX-XXX', max_length=9, validators=[django.core.validators.RegexValidator(message='CEP inválido. Use o formato XXXXX-XXX ou XXXXXXXX.', regex='^\\d{5}-?\\d{3}$')], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.IntegerField(null=True),
        ),
    ]
