# Generated by Django 5.1.7 on 2025-04-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_remove_usuario_unique_email_remove_usuario_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(null=True),
        ),
    ]
