# Generated by Django 5.1.7 on 2025-05-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_remove_endereco_pais_remove_endereco_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='pais',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
