# Generated by Django 5.1.7 on 2025-05-08 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_endereco_pais'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Endereco',
            new_name='Endereco_usuario',
        ),
    ]
