# Generated by Django 5.1.7 on 2025-05-13 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_rename_endereco_endereco_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chacara',
        ),
    ]
